### ISSUE TITLE
Separate `Concept` and `Collection` in `get_concepts`

### ISSUE THREAD

**Issue by sami-m-g** [Depart-de-Sentier/dds_glossary#43]

**Comment by sami-m-g** [comment]
@cmutel @jsvgoncalves after adding support for `Collection`, the `get_concepts` endpoint returns all `Collection` and `Concept` instances in the provided scheme. Currently we don't have any datasets that includes collections, but should we keep returning both entities and maybe add a field with `type` or should we separate it to 2 endpoints: `get_concepts` and `get_collections`?

**Comment by jsvgoncalves** [comment]
Having two separate endpoints feels like a better API design. Are there any advantages in the first option you mentioned?

**Comment by sami-m-g** [comment]
@jsvgoncalves I second the point of having a better API design, but on investigating this more, I suggest ending up with 3 endpoints: `get_concepts`, `get_collections` and `get_concept_scheme`. Where the last one includes some details on the concept scheme that currently no API endpoint make plus 2 lists: `collections` and `concepts`. TBH, should have been the case from the beginning.

**Comment by cmutel** [comment]
@sami-m-g Can you give some more information on what a `Collection` is?

**Comment by sami-m-g** [comment]
@cmutel as per  https://www.w3.org/TR/skos-reference/#collections:
_"SKOS concept collections are labeled and/or ordered groups of SKOS concepts.
Collections are useful where a group of concepts shares something in common, and it is convenient to group them under a common label, or where some concepts can be placed in a meaningful order."_
Basically a `Collection` can have an `in_scheme` relation with multiple `ConceptScheme` same as a `Concept`. And a `Concept` can have an `in_collection` relation with multiple `Collection`. Furthermore, nested `Collection` relation is accepted, i.e. a `Collection` can have an `in_collection` relation with multiple `Collection`.
