### ISSUE TITLE
Add FAOSTAT Commodity List (FCL) dataset

### ISSUE THREAD

**Issue by sami-m-g** [Depart-de-Sentier/dds_glossary#6]
@cmutel according to https://github.com/Depart-de-Sentier/dds_glossary/issues/6#issue-2288362915: _"FCL was discontinued in 1994, it is kept for legacy but its use in new statistical activities is deprecated. "_. Do we still want to include this dataset?

**Comment by cmutel** [comment]
Going to need some more information to help out here :)

**Comment by sami-m-g** [comment]
Seems like the issue description wasn't saved. I've updated it now!

**Comment by cmutel** [comment]
No
